name: terraform gcp pipeline

on:
  push:
    branches: [main]
  workflow_dipatch:

  jobs:
    terraform:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.5.6

        -name: Authenticate to GCP
         uses: google-github-actions/auth@v1
         with:
           credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        -name: setup gcp project
         run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

         -name: Terraform Init
          run: terraform init

          - name: Terraform Plan
           run: terraform plan

           -name: Terraform plan
            run: terraform plan

            -name: Terraform Apply
             if: github.ref == 'refs/heads/main'
             run: terraform apply -auto-approve
